ProductosDeLimpieza = ["Papel Higenico", "Papel De Cocina", "Detergente", "Jabon", "Trapo de Piso", "Suavizante", "Lavandina"]
Mercaderia = ["Arroz", "Fideos", "Lentejas", "Arvejas", "Pure de Tomate", "Pan", "Choclo"]
Frutas = ["Manzana", "Naranjas", "Limones", "Mandarinas", "Bananas", "Tomates"]
Verduras = ["Papas", "Cebollas", "Zanahorias", "Ajo", "Pimiento"]
ProductosExtras = ["Mayonesa", "Jugo", "Crema", "Dulce De Leche", "Mermelada", "Yogurt"]

print()
print(ProductosDeLimpieza)
print("---------------------------------------------------------")
print(Mercaderia)
print("---------------------------------------------------------")
print(Frutas)
print("---------------------------------------------------------")
print(Verduras)
print("---------------------------------------------------------")
print(ProductosExtras)
print("---------------------------------------------------------")

print()
CantidadProdLimpieza = len(ProductosDeLimpieza)
print("Cantidad de productos de limpieza a comprar ",CantidadProdLimpieza)
print("---------------------------------------------------------")
CantidadMercaderia = len(Mercaderia)
print("Cantidad de productos de mercaderia a comprar ",CantidadMercaderia)
print("---------------------------------------------------------")
CantidadFrutas = len(Frutas)
print("Cantidad de frutas a comprar ", CantidadFrutas)
print("---------------------------------------------------------")
CantidadVerduras = len(Verduras)
print("Cantidad de verduras a comprar ", CantidadFrutas)
print("---------------------------------------------------------")
CantidadExtra = len(ProductosExtras)
print("Cantidad de productos extras a comprar ", CantidadExtra)
print("---------------------------------------------------------")
Total = len(ProductosDeLimpieza + ProductosExtras + Verduras + Frutas + Mercaderia)
print("Cantidad de productos Total a traer ",Total)
print("---------------------------------------------------------")

print()
ProductosDeLimpieza.append("Jabon Blanco")
print(ProductosDeLimpieza)
print("---------------------------------------------------------")
Mercaderia.append("Atun")
print(Mercaderia)
print("---------------------------------------------------------")
Frutas.append("Uvas")
print(Frutas)
print("---------------------------------------------------------")
Verduras.append("Pimiento")
print(Verduras)
print("---------------------------------------------------------")
ProductosExtras.append("Galletas")
print(ProductosExtras)
print("---------------------------------------------------------")

print()
ProductosDeLimpieza.extend(["Broches","Pasta Dental"])
print(ProductosDeLimpieza)
print("---------------------------------------------------------")
Mercaderia.extend(["Sopa", "Polenta", "Porotos"])
print(Mercaderia)
print("---------------------------------------------------------")
Frutas.extend(["Melon", "Sandia", "Pomelo", "Damasco", "Pera"])
print(Frutas)
print("---------------------------------------------------------")
Verduras.extend(["Berenjena", "Tomate"])
print("---------------------------------------------------------")
print(Verduras)
ProductosExtras.extend(["Chocolate", "Gomitas"])
print(ProductosExtras)

print()
CantidadProdLimpieza = len(ProductosDeLimpieza)
print("Cantidad Total de Productos de Limpieza a comprar: ", CantidadProdLimpieza)
print("---------------------------------------------------------")
CantidadMercaderia = len(Mercaderia)
print("Cantidad Total de Mercaderia a comprar: ", CantidadMercaderia)
print("---------------------------------------------------------")
CantidadFrutas = len(Frutas)
print("Cantidad Total de Frutas a comprar: ", CantidadFrutas)
print("---------------------------------------------------------")
CantidadVerduras = len(Verduras)
print("Cantidad Total de Verduras a comprar: ", CantidadVerduras)
print("---------------------------------------------------------")
CantidadExtra = len(ProductosExtras)
print("Cantidad Total de Productos extras a comprar: ", CantidadExtra)
print("---------------------------------------------------------")

print()
ProductosDeLimpieza.pop(5)
print("Nueva lista de Productos de limpieza: ", ProductosDeLimpieza)
print("---------------------------------------------------------")
Mercaderia.pop(8)
print("Nueva lista de Mercaderia: ", Mercaderia)
print("---------------------------------------------------------")
Frutas.pop(7)
print("Nueva lista de frutas: ", Frutas)
print("---------------------------------------------------------")
Verduras.pop(2)
print("Nueva lista de verduras: ", Verduras)
print("---------------------------------------------------------")
ProductosExtras.pop(1)
print("Nueva lista de Productos a comprar ", ProductosExtras)
print("---------------------------------------------------------")